all:
  vars:
    control_plane_endpoint: 192.168.0.100
    load_balancer_ip_pool:
      - 192.168.0.224/27
metal:
  children:
    masters:
      hosts:
        node01: {ansible_host: 192.168.0.5, mac: '08:00:27:c0:96:6f', disk: sda, network_interface: enp0s3}
    workers:
      hosts:
        node02: {ansible_host: 192.168.0.6, mac: '08:00:27:64:b6:f9', disk: sda, network_interface: enp0s3}
