all:
  vars:
    control_plane_endpoint: 192.168.0.100
    load_balancer_ip_pool:
      - 192.168.0.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.5, mac: '08:00:27:C0:96:6F', disk: sda, network_interface: enp0s3}
    workers:
      hosts:
        metal1: {ansible_host: 192.168.0.6, mac: '08:00:27:64:B6:F9', disk: sda, network_interface: enp0s3}
        metal2: {ansible_host: 192.168.0.7, mac: '08:00:27:C3:B2:09', disk: sda, network_interface: enp0s3}
